# Generated by Django 5.2.3 on 2025-06-27 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PelayananKategorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/pelkat/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/pelkat/')),
            ],
            options={
                'verbose_name': 'Pelayanan Kategorial',
                'verbose_name_plural': 'Pelayanan Kategorial',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/pelkat/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('pelkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='pelkat.pelayanankategorial')),
            ],
        ),
        migrations.CreateModel(
            name='PelkatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/pelkat/')),
                ('pelkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pelkat.pelayanankategorial')),
            ],
            options={
                'verbose_name': 'Event Pelkat',
                'verbose_name_plural': 'Event Pelkat',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pengurus/pelkat/')),
                ('pelkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengurus', to='pelkat.pelayanankategorial')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('pelkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pelkat.pelayanankategorial')),
            ],
        ),
    ]
