# Generated by Django 5.2.3 on 2025-06-28 03:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelkat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelayanankategorial',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
