# Generated by Django 5.2.3 on 2025-06-28 04:29

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelkat', '0002_alter_pelayanankategorial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelkatevent',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.CreateModel(
            name='PelkatEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/pelkat/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pelkat.pelkatevent')),
            ],
            options={
                'verbose_name': 'Foto Event Pelkat',
                'verbose_name_plural': 'Foto-Foto Event Pelkat',
            },
        ),
    ]
