# Generated by Django 5.2.3 on 2025-06-28 09:47

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelkat', '0003_alter_pelkatevent_description_pelkateventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pelkateventimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
