# Generated by Django 5.2.3 on 2025-06-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelkat', '0004_schedule_description_schedule_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurus',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
