# Generated by Django 5.2.3 on 2025-06-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelkat', '0005_pengurus_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengurus',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Masukkan nomor WhatsApp tanpa spasi atau tanda +, misalnya: 6281944848000', max_length=20, null=True),
        ),
    ]
