# Generated by Django 5.2.3 on 2025-06-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('ikon', models.CharField(help_text='Gunakan nama ikon bootstrap atau ikon FontAwesome.', max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('url_target', models.CharField(blank=True, help_text="Contoh: 'pelkat-index', 'musik:index'", max_length=100)),
            ],
        ),
    ]
